# Generated by Django 3.0.3 on 2020-04-01 18:18
# Generated by Django 3.0.3 on 2020-04-01 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobInfo',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=250)),
                ('job_description', models.TextField(blank=True, null=True)),
                ('job_status', models.CharField(choices=[('PENDING', 'Pending'), ('DECLINED', 'Declined'), ('MATCHED', 'Matched'), ('PAID', 'Paid'), ('CANCELLED_BY_PHOTOGRAPHER', 'Cancelled by photographer'), ('CANCELLED_BY_CUSTOMER', 'Cancelled by customer'), ('PROCESSING', 'Processing Photos'), ('COMPLETED', 'Completed'), ('CLOSED', 'Closed'), ('REVIEWED', 'Reviewed')], default='PENDING', max_length=25)),
                ('job_style', models.CharField(choices=[('GRADUATION', 'Graduation'), ('LANDSCAPE', 'Landscape'), ('PORTRAIT', 'Portrait'), ('PRODUCT', 'Product'), ('FASHION', 'Fashion'), ('EVENT', 'Event'), ('WEDDING', 'Wedding'), ('NONE', 'None')], max_length=15)),
                ('job_location', models.CharField(max_length=400)),
                ('job_expected_complete_date', models.DateField()),
                ('job_special_requirement', models.CharField(blank=True, max_length=400, null=True)),
                ('job_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photoshoot_date', models.DateField()),
                ('photoshoot_time', models.CharField(choices=[('HALF_DAY_MORNING', 'Half-day(Morning-Noon)'), ('HALF_DAY_NOON', 'Half-day(Noon-Evening)'), ('FULL_DAY', 'Full-Day'), ('NIGHT', 'Night'), ('FULL_DAY_NIGHT', 'Full-Day and Night')], max_length=20)),
            ],
        ),
    ]
